### ISSUE TITLE
Second multichoice question on Step 5 - Confirmation does not work correctly

### ISSUE THREAD

**Issue by noisyjerm** [dkilfoyle/thrombolysis#3]
On Step 5 - Confirmation (http://dkilfoyle.github.io/thrombolysis/docs/s5confirmation/) the second multichoice question (45y old smoker), feedback is not given - instead feedback appears for the first question (51 female)

Adding an id attribute should fix this. I don't have the necessary tools to test it but i think something like this should work:

51 female. Longstanding hypertension on 3 drugs. Woke up, had shower, collapsed walking to kitchen. Drowsy, R) hemiplegia. BP 200/95. What should be the next step? {: .MCQ #q1}

45y old smoker. BIB found by neighbour collapsed on kitchen floor. O/E drowsy, mute, right hemiplegia. CT as shown. Which is correct? {: .MCQ #q2}

**Comment by dkilfoyle** [comment]
Thanks - you are right: the 45y feedback was appearing in the 51y area. The problem was the MCQ question was not preceeded by ### (the markdown symbol for heading level 3). The MCQ javascript needs this to find the questions/answers as children of the H3. Should be fixed now.

The format for MCQs should be

### Ask the question here?

{: .MCQ}
- Option 1 text here
- Response to selecting option 1 here
- Option 2 text here
- Response to selecting option 2 here
